# send_email.py
import os
import smtplib
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from pathlib import Path


def get_test_summary(log_path):
    """从日志文件中提取设备、版本、测试结果"""
    if not log_path.exists():
        print(f"❌ Log file not found: {log_path}")
        return "Unknown", "Unknown", 0, 0

    device = version = "Unknown"
    passed = failed = 0

    # 读取整个日志内容
    try:
        with open(log_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
    except Exception as e:
        print(f"❌ Failed to read log: {e}")
        return device, version, passed, failed

    # 1. 从日志内容中找 Device Type 和 Software Version
    for line in lines:
        if "Device Type:" in line and "Software Version:" in line:
            match = re.search(r"Device Type:\s*(\S+),\s*Software Version:\s*(\S+)", line)
            if match:
                device = match.group(1)
                version = match.group(2)
                break

    # 2. 找 Summary 行
    for line in lines:
        if "Summary:" in line:
            match = re.search(r"Summary:\s*(\d+)\s+passed,\s+(\d+)\s+failed", line)
            if match:
                passed = int(match.group(1))
                failed = int(match.group(2))
                break

    print(f"✅ Parsed: Device={device}, Version={version}, Passed={passed}, Failed={failed}")
    return device, version, passed, failed


def main():
    # 从 Jenkins environment 读取
    sender_email = os.getenv("QQ_EMAIL")
    password = os.getenv("QQ_AUTH_CODE")
    receiver_email = os.getenv("RECIPIENT")
    log_file = os.getenv("LOG_FILE")

    if not all([sender_email, password, receiver_email, log_file]):
        print("❌ Missing environment variables: QQ_EMAIL, QQ_AUTH_CODE, RECIPIENT, LOG_FILE")
        exit(1)

    log_path = Path(log_file)
    device, version, passed, failed = get_test_summary(log_path)

    # 构建邮件内容
    subject = f"[Jenkins CI] {device} {version} | PASS: {passed} / FAIL: {failed}"
    body = f"""\
Automated Test Report

Device Type: {device}
Software Version: {version}
Test Result: {passed} passed, {failed} failed
Log File: {log_path.name}

Generated by Jenkins at: {log_path.parent}
"""

    # 发送邮件
    try:
        print(f"📧 Sending email from {sender_email} to {receiver_email}...")
        server = smtplib.SMTP("smtp.qq.com", 587, timeout=15)
        server.starttls()
        server.login(sender_email, password)
        msg = MIMEMultipart()
        msg["From"] = sender_email
        msg["To"] = receiver_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("✅ Email sent successfully.")
    except Exception as e:
        print(f"❌ Failed to send email: {e}")
        exit(1)


if __name__ == "__main__":
    main()