import os
import smtplib
import re
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path

def get_test_summary(log_path):
    if not log_path.exists():
        print("Log file not found: " + str(log_path))
        return "Unknown", "Unknown", 0, 0

    device = version = "Unknown"
    passed = failed = 0

    try:
        with open(log_path, "r", encoding="utf-8") as f:
            lines = f.readlines()
            for line in lines:
                if "Device Type:" in line and "Software Version:" in line:
                    match = re.search(r"Device Type:\s*(\S+),\s*Software Version:\s*(\S+)", line)
                    if match:
                        device = match.group(1)
                        version = match.group(2)
                elif "Summary:" in line:
                    match = re.search(r"Summary:\s*(\d+)\s+passed,\s+(\d+)\s+failed", line)
                    if match:
                        passed = int(match.group(1))
                        failed = int(match.group(2))
    except Exception as e:
        print("Failed to read log: " + str(e))

    print("Parsed: Device=" + device + ", Version=" + version + ", Passed=" + str(passed) + ", Failed=" + str(failed))
    return device, version, passed, failed

def main():
    sender_email = os.getenv("QQ_EMAIL")
    password = os.getenv("QQ_AUTH_CODE")
    receiver_email = os.getenv("RECIPIENT")
    log_file = os.getenv("LOG_FILE")
    detailed_log_path = os.getenv("DETAILED_LOG_PATH")

    if not all([sender_email, password, receiver_email, log_file]):
        print("Missing environment variables")
        exit(1)

    log_path = Path(log_file)
    detailed_log = Path(detailed_log_path) if detailed_log_path else None

    device, version, passed, failed = get_test_summary(log_path)

    subject = "[Jenkins CI] " + device + " " + version + " | PASS: " + str(passed) + " / FAIL: " + str(failed)
    body = "Automated Test Report\n\n" \
           "Device Type: " + device + "\n" \
           "Software Version: " + version + "\n" \
           "Test Result: " + str(passed) + " passed, " + str(failed) + " failed\n" \
           "Log File: " + log_path.name + "\n\n" \
           "Generated by Jenkins at: " + str(log_path.parent)

    msg = MIMEMultipart()
    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    if detailed_log and detailed_log.exists():
        try:
            with open(detailed_log, "rb") as attachment:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(attachment.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                "attachment; filename=" + detailed_log.name
            )
            msg.attach(part)
            print("Attached: " + str(detailed_log))
        except Exception as e:
            print("Failed to attach log: " + str(e))

    try:
        server = smtplib.SMTP("smtp.qq.com", 587, timeout=15)
        server.starttls()
        server.login(sender_email, password)
        server.sendmail(sender_email, receiver_email, msg.as_string())
        server.quit()
        print("Email sent successfully")
    except Exception as e:
        print("Failed to send email: " + str(e))
        exit(1)

if __name__ == "__main__":
    main()